name: deploy
on: 
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'      
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './infra'
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: terraform init
        run: terraform init -backend=true -backend-config=variables/dev/backend.hcl
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: terraform plan
         id: plan
        run: |
          terraform plan -input=false -no-color -out=tfplan \
          && terraform show -no-color tfplan

      - name: Apply Terraform
        if: steps.plan.outcome == 'success'
        id: apply
        continue-on-error: true
        working-directory: ./infra
        run: |
          terraform apply \
            -input=false \
            -no-color \
            tfplan           
            
